openapi: 3.0.0
info:
  title: StudentInt
  description: Group work 3
  version: 1.0.0
tags:
  - name: student
    description: interface involbe student object
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /student:
    put:
      tags:
        - student
      summary: submit a assignment
      description: submit a assignment with a specific file url
      operationId: submit
      requestBody:
        description: submit a assignment with a specific file url
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Assignment'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
               type: string
               example: subNr
        '400':
          description: Invalid ID supplied
        '404':
          description: url not found
        '405':
          description: Validation exception
  /student/{subNr}:
    get:
      tags:
        - student
      summary: get feedback
      description: get feedback on a specific submission number
      operationId: getFeedback
      parameters:
        - name: subNr
          in: path
          description: submission number
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
            application/xml:
              schema:
                $ref: '#/components/schemas/Feedback'
        '405':
          description: Invalid input
  /student/{id}/{moduleId}:
    get:
      tags:
        - student
      summary: get a specific student's all feedback on a specific module
      description: get a specific student's all feedback on a specific module
      operationId: getModuleFeedback
      parameters:
        - name: id
          in: path
          description: student id
          required: true
          explode: true
          schema:
            type: string
        - name: moduleId
          in: path
          description: module id
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'
        '400':
          description: Invalid status value
  /file/:
    post:
      summary: Receive file
      description: Receives a file stream and return a URL
      operationId: ReceiveFile
      parameters:
        - name: filename
          in: query
          description: file name
          required: true
          schema:
            type: string
      requestBody:
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          required: true
      responses:
        '200':
          description: OK (200)
          content:
            application/json:
              schema:
                type: string
  /file/{filename}:
    get:
      summary: Returns the contents of a file as a file stream
      description: Retrieve the file from the URL
      operationId: ReturnFile
      responses:
        '200':
          description: OK (200)
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

components:
  schemas:
    Assignment:
      type: object
      properties:
        id:
          type: string
          example: student id
        url:
          type: string
          example: http://xxxx.xxxx
        dueDate:
          type: string
          format: date-time
      xml:
        name: Assignment
    Feedback:
      type: object
      properties:
        subNr:
          type: string
          example: submission Id
        text:
          type: string
          example: xxxxxx
        mark:
          type: integer
          format: int64
          example: 75
      xml:
        name: Feedback